// <auto-generated />
using System;
using CRM.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Data.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Data.Models.ActividadLog", b =>
                {
                    b.Property<long>("nActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_actividad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nActividad"));

                    b.Property<string>("cAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_accion");

                    b.Property<string>("cEntidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("c_entidad");

                    b.Property<string>("cValorAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_valor_anterior");

                    b.Property<string>("cValorNuevo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_valor_nuevo");

                    b.Property<DateTime>("dFecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha");

                    b.Property<long>("nEntidadId")
                        .HasColumnType("bigint")
                        .HasColumnName("n_entidad_id");

                    b.Property<int?>("nUsuario")
                        .HasColumnType("int")
                        .HasColumnName("n_usuario");

                    b.HasKey("nActividad");

                    b.HasIndex("nUsuario");

                    b.HasIndex("cEntidad", "nEntidadId");

                    b.ToTable("crm_actividad_log", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Campana", b =>
                {
                    b.Property<long>("nCampana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_campana");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nCampana"));

                    b.Property<string>("cDescripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_descripcion");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_tipo");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<DateTime?>("dFechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_fin");

                    b.Property<DateTime>("dFechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_inicio");

                    b.Property<int?>("nAsignadoA")
                        .HasColumnType("int")
                        .HasColumnName("n_asignado_a");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nCampana");

                    b.HasIndex("nAsignadoA");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_campana", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.CampanaCliente", b =>
                {
                    b.Property<long>("nCampana")
                        .HasColumnType("bigint")
                        .HasColumnName("n_campana");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_estado");

                    b.Property<DateTime>("dFechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_asignacion");

                    b.HasKey("nCampana", "nCliente");

                    b.HasIndex("nCliente");

                    b.ToTable("crm_campana_cliente", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Cliente", b =>
                {
                    b.Property<long>("nCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nCliente"));

                    b.Property<string>("cCanalOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_canal_origen");

                    b.Property<string>("cDocumento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_documento");

                    b.Property<string>("cEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_email");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cFotoPerfilUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_foto_perfil_url");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_telefono");

                    b.Property<DateTime>("dFechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_registro");

                    b.HasKey("nCliente");

                    b.ToTable("crm_cliente", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ClienteEtiqueta", b =>
                {
                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<int>("nEtiqueta")
                        .HasColumnType("int")
                        .HasColumnName("n_etiqueta");

                    b.Property<DateTime>("dFechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_asignacion");

                    b.HasKey("nCliente", "nEtiqueta");

                    b.HasIndex("nEtiqueta");

                    b.ToTable("crm_cliente_etiqueta", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Conversacion", b =>
                {
                    b.Property<long>("nConversacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nConversacion"));

                    b.Property<string>("cBotEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_bot_estado");

                    b.Property<string>("cCanal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(32)
                        .HasColumnName("c_canal");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cExternalThreadId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_external_thread_id");

                    b.Property<DateTime?>("dBotPausadoDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_bot_pausado_desde");

                    b.Property<DateTime>("dFechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_inicio");

                    b.Property<DateTime?>("dUltimoMensaje")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_ultimo_mensaje");

                    b.Property<DateTime?>("dUltimoMensajeCliente")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_ultimo_mensaje_cliente");

                    b.Property<int?>("nBotPausadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_bot_pausado_por");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<int?>("nUsuarioAsignado")
                        .HasColumnType("int")
                        .HasColumnName("n_usuario_asignado");

                    b.HasKey("nConversacion");

                    b.HasIndex("nCliente");

                    b.HasIndex("nUsuarioAsignado");

                    b.ToTable("crm_conversacion", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.CrmUsuario", b =>
                {
                    b.Property<int>("nUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("n_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nUsuario"));

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cPasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_password_hash");

                    b.Property<string>("cRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_rol");

                    b.Property<string>("cUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_usuario");

                    b.HasKey("nUsuario");

                    b.ToTable("crm_usuario", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Etiqueta", b =>
                {
                    b.Property<int>("nEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("n_etiqueta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nEtiqueta"));

                    b.Property<string>("cColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_color");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("c_nombre");

                    b.HasKey("nEtiqueta");

                    b.HasIndex("cNombre")
                        .IsUnique();

                    b.ToTable("crm_etiqueta", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.KpiDashboard", b =>
                {
                    b.Property<long>("nKpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_kpi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nKpi"));

                    b.Property<string>("cMeta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_meta");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cPeriodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_periodo");

                    b.Property<string>("cTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_tipo");

                    b.Property<string>("cValor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_valor");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_creacion");

                    b.HasKey("nKpi");

                    b.ToTable("crm_kpi_dashboard", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Mensaje", b =>
                {
                    b.Property<long>("nMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_mensaje");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nMensaje"));

                    b.Property<string>("cCanal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_canal");

                    b.Property<string>("cDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("c_direccion");

                    b.Property<string>("cEstado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cExternalId")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(450)
                        .HasColumnName("c_external_id");

                    b.Property<string>("cMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_mensaje");

                    b.Property<string>("cTipo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_tipo");

                    b.Property<string>("cWhatsappId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_whatsapp_id");

                    b.Property<DateTime>("dFecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha");

                    b.Property<long>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.HasKey("nMensaje");

                    b.HasIndex("nConversacion");

                    b.HasIndex("cCanal", "cDireccion", "cExternalId")
                        .IsUnique()
                        .HasFilter("[c_direccion] = 'E' AND [c_external_id] IS NOT NULL");

                    b.ToTable("crm_mensaje", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.NotaInterna", b =>
                {
                    b.Property<long>("nNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_nota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nNota"));

                    b.Property<string>("cTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_texto");

                    b.Property<DateTime>("dFecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<long?>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.Property<int>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nNota");

                    b.HasIndex("nCliente");

                    b.HasIndex("nConversacion");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_nota_interna", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Oportunidad", b =>
                {
                    b.Property<long>("nOportunidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_oportunidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nOportunidad"));

                    b.Property<string>("cEtapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_etapa");

                    b.Property<string>("cMoneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_moneda");

                    b.Property<string>("cMotivoPerdida")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_motivo_perdida");

                    b.Property<string>("cTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_titulo");

                    b.Property<DateTime?>("dFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_actualizacion");

                    b.Property<DateTime?>("dFechaCierreEstimada")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_cierre_estimada");

                    b.Property<DateTime?>("dFechaCierreReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_cierre_real");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<long?>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.Property<decimal>("nMonto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("n_monto");

                    b.Property<int>("nProbabilidad")
                        .HasColumnType("int")
                        .HasColumnName("n_probabilidad");

                    b.Property<int?>("nUsuarioAsignado")
                        .HasColumnType("int")
                        .HasColumnName("n_usuario_asignado");

                    b.HasKey("nOportunidad");

                    b.HasIndex("nCliente");

                    b.HasIndex("nConversacion");

                    b.HasIndex("nUsuarioAsignado");

                    b.ToTable("crm_oportunidad", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ReglaAutomatica", b =>
                {
                    b.Property<long>("nRegla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_regla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nRegla"));

                    b.Property<bool>("bActiva")
                        .HasColumnType("bit")
                        .HasColumnName("b_activa");

                    b.Property<string>("cAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_accion");

                    b.Property<string>("cCondicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_condicion");

                    b.Property<string>("cEntidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_entidad");

                    b.Property<string>("cEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_evento");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cValorAccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_valor_accion");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<int?>("nAsignadoA")
                        .HasColumnType("int")
                        .HasColumnName("n_asignado_a");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nRegla");

                    b.HasIndex("nAsignadoA");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_regla_automatica", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ReporteExportacion", b =>
                {
                    b.Property<long>("nReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nReporte"));

                    b.Property<string>("cEntidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_entidad");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_ruta");

                    b.Property<string>("cTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_tipo");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nReporte");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_reporte_exportacion", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Tarea", b =>
                {
                    b.Property<long>("nTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_tarea");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nTarea"));

                    b.Property<string>("cDescripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_descripcion");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_titulo");

                    b.Property<DateTime?>("dFechaCompletada")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_completada");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<DateTime>("dFechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_fecha_vencimiento");

                    b.Property<int?>("nAsignadoA")
                        .HasColumnType("int")
                        .HasColumnName("n_asignado_a");

                    b.Property<long?>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<long?>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.Property<long?>("nOportunidad")
                        .HasColumnType("bigint")
                        .HasColumnName("n_oportunidad");

                    b.HasKey("nTarea");

                    b.HasIndex("nAsignadoA");

                    b.HasIndex("nCliente");

                    b.HasIndex("nConversacion");

                    b.HasIndex("nOportunidad");

                    b.ToTable("crm_tarea", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ActividadLog", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("nUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRM.Data.Models.Campana", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("nAsignadoA")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AsignadoA");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.CampanaCliente", b =>
                {
                    b.HasOne("CRM.Data.Models.Campana", "Campana")
                        .WithMany()
                        .HasForeignKey("nCampana")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campana");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CRM.Data.Models.ClienteEtiqueta", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Etiqueta", "Etiqueta")
                        .WithMany("Clientes")
                        .HasForeignKey("nEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("CRM.Data.Models.Conversacion", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany("Conversaciones")
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.CrmUsuario", "UsuarioAsignado")
                        .WithMany("ConversacionesAsignadas")
                        .HasForeignKey("nUsuarioAsignado");

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("CRM.Data.Models.Mensaje", b =>
                {
                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("CRM.Data.Models.NotaInterna", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Conversacion");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.Oportunidad", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "UsuarioAsignado")
                        .WithMany()
                        .HasForeignKey("nUsuarioAsignado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Conversacion");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("CRM.Data.Models.ReglaAutomatica", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("nAsignadoA")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AsignadoA");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.ReporteExportacion", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.Tarea", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("nAsignadoA")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.Oportunidad", "Oportunidad")
                        .WithMany()
                        .HasForeignKey("nOportunidad")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AsignadoA");

                    b.Navigation("Cliente");

                    b.Navigation("Conversacion");

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("CRM.Data.Models.Cliente", b =>
                {
                    b.Navigation("Conversaciones");
                });

            modelBuilder.Entity("CRM.Data.Models.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("CRM.Data.Models.CrmUsuario", b =>
                {
                    b.Navigation("ConversacionesAsignadas");
                });

            modelBuilder.Entity("CRM.Data.Models.Etiqueta", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
