/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'catalog': RouteRecordInfo<'catalog', '/catalog', Record<never, never>, Record<never, never>>,
    'catalog-resource': RouteRecordInfo<'catalog-resource', '/catalog/:resource', { resource: ParamValue<true> }, { resource: ParamValue<false> }>,
    'catalog-additional-characteristics': RouteRecordInfo<'catalog-additional-characteristics', '/catalog/additional-characteristics', Record<never, never>, Record<never, never>>,
    'catalog-finishes': RouteRecordInfo<'catalog-finishes', '/catalog/finishes', Record<never, never>, Record<never, never>>,
    'catalog-lengths': RouteRecordInfo<'catalog-lengths', '/catalog/lengths', Record<never, never>, Record<never, never>>,
    'catalog-products': RouteRecordInfo<'catalog-products', '/catalog/products', Record<never, never>, Record<never, never>>,
    'catalog-subtypes': RouteRecordInfo<'catalog-subtypes', '/catalog/subtypes', Record<never, never>, Record<never, never>>,
    'catalog-types-id': RouteRecordInfo<'catalog-types-id', '/catalog/types/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contact': RouteRecordInfo<'contact', '/contact', Record<never, never>, Record<never, never>>,
    'customers-add': RouteRecordInfo<'customers-add', '/customers/add', Record<never, never>, Record<never, never>>,
    'customers-edit-id': RouteRecordInfo<'customers-edit-id', '/customers/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'customers-list': RouteRecordInfo<'customers-list', '/customers/list', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'promotions': RouteRecordInfo<'promotions', '/promotions', Record<never, never>, Record<never, never>>,
    'promotions-id': RouteRecordInfo<'promotions-id', '/promotions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'promotions-id-results': RouteRecordInfo<'promotions-id-results', '/promotions/:id/results', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'promotions-add': RouteRecordInfo<'promotions-add', '/promotions/add', Record<never, never>, Record<never, never>>,
    'promotions-edit-id': RouteRecordInfo<'promotions-edit-id', '/promotions/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'promotions-manage': RouteRecordInfo<'promotions-manage', '/promotions/manage', Record<never, never>, Record<never, never>>,
    'quotations-id': RouteRecordInfo<'quotations-id', '/quotations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'quotations-add': RouteRecordInfo<'quotations-add', '/quotations/add', Record<never, never>, Record<never, never>>,
    'quotations-list': RouteRecordInfo<'quotations-list', '/quotations/list', Record<never, never>, Record<never, never>>,
    'users-list': RouteRecordInfo<'users-list', '/users/list', Record<never, never>, Record<never, never>>,
  }
}
