export default [
  { heading: 'Clientes', roles: ['admin', 'commercial'] },
  {
    title: 'Listar Empresas',
    to: { name: 'customers-list' },
    icon: { icon: 'ri-id-card-line' },
    action: 'read',
    subject: 'Customer',
    roles: ['admin', 'commercial'],
  },
  {
    title: 'Usuarios',
    to: { name: 'users-list' },
    icon: { icon: 'ri-user-settings-line' },
    action: 'read',
    subject: 'User',
    roles: ['admin', 'commercial'],
  },
  { heading: 'Promociones', roles: ['admin'] },
  {
    title: 'Gestionar Publicaciones',
    to: { name: 'promotions-manage' },
    icon: { icon: 'ri-file-edit-line' },
    action: 'read',
    subject: 'Promotion',
    roles: ['admin'],
  },
  { heading: 'Catálogo', roles: ['admin'] },
  {
    title: 'Tipos de productos',
    to: { path: '/catalog/types' },
    icon: { icon: 'ri-layout-grid-line' },
    action: 'read',
    subject: 'Catalog',
    roles: ['admin'],
  },
  {
    title: 'Subtipos',
    to: { path: '/catalog/subtypes' },
    icon: { icon: 'ri-node-tree' },
    action: 'read',
    subject: 'Catalog',
    roles: ['admin'],
  },
  {
    title: 'Productos',
    to: { path: '/catalog/products' },
    icon: { icon: 'ri-box-3-line' },
    action: 'read',
    subject: 'Catalog',
    roles: ['admin'],
  },
  {
    title: 'Acabados',
    to: { path: '/catalog/finishes' },
    icon: { icon: 'ri-palette-line' },
    action: 'read',
    subject: 'Catalog',
    roles: ['admin'],
  },
  {
    title: 'Longitudes',
    to: { path: '/catalog/lengths' },
    icon: { icon: 'ri-expand-width-line' },
    action: 'read',
    subject: 'Catalog',
    roles: ['admin'],
  },
  {
    title: 'Características',
    to: { path: '/catalog/additional-characteristics' },
    icon: { icon: 'ri-list-check-3' },
    action: 'read',
    subject: 'Catalog',
    roles: ['admin'],
  },
]
